window.SEARCH_INDEX = [
  {
    "id": "v2x-overview",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "V2X Communication Overview & Cooperative ITS",
    "module": "Vehicular Communications & V2X",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/automotive-communication/v2x-overview.html",
    "summary": "Vehicle-to-Everything (V2X) communication is the cornerstone of Cooperative Intelligent Transport Systems (C-ITS). It extends a vehicle's situational awareness beyond the direct li",
    "keywords": "V2X Communication Overview & Cooperative ITS Vehicular Communications & V2X Beginner Automotive Communication Systems AELZG513 End-to-End Latency Requirement for Safety Messages What is the primary difference between onboard ADAS sensors and V2X communication? What are the four core sub-domains of V2X? Explain the complete architectural framework of V2X communication, detailing message types, frequency bands, and active safety use cases with a suitable block diagram."
  },
  {
    "id": "dsrc-vs-cv2x",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "DSRC (IEEE 802.11p) vs Cellular V2X (C-V2X / 5G NR)",
    "module": "Vehicular Communications & V2X",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/dsrc-vs-cv2x.html",
    "summary": "The automotive industry and international standards bodies have developed two competing physical/link layer technologies for direct vehicular safety communications: Dedicated Short",
    "keywords": "DSRC (IEEE 802.11p) vs Cellular V2X (C-V2X / 5G NR) Vehicular Communications & V2X Intermediate Automotive Communication Systems AELZG513 Link Budget & Path Loss Advantage Why does C-V2X Mode 4 perform better than DSRC in dense vehicular traffic? Does C-V2X direct communication require a cellular SIM card or tower coverage? Provide an exhaustive comparison between DSRC (IEEE 802.11p) and C-V2X (3GPP Release 14/16), analyzing PHY/MAC layers, link budgets, and congestion handling mechanisms."
  },
  {
    "id": "wireless-channel-propagation",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "Wireless Channel Propagation & Large-Scale Fading",
    "module": "Wireless Fundamentals & Channel Models",
    "level": "Intermediate",
    "importance": 4,
    "url": "topics/automotive-communication/wireless-channel-propagation.html",
    "summary": "In automotive wireless communications, radio frequency (RF) electromagnetic waves propagate through dynamic, cluttered environments consisting of moving vehicles, roadside building",
    "keywords": "Wireless Channel Propagation & Large-Scale Fading Wireless Fundamentals & Channel Models Intermediate Automotive Communication Systems AELZG513 Friis Free Space Path Loss Equation Critical Crossover Distance (Two-Ray Model) What is the critical crossover distance in vehicular two-ray ground propagation? What causes log-normal shadowing in vehicular communication? Derive the Two-Ray Ground Reflection model and explain its physical significance in V2X highway communication links."
  },
  {
    "id": "small-scale-fading-doppler",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "Small-Scale Fading, RMS Delay Spread & Doppler Effect",
    "module": "Wireless Fundamentals & Channel Models",
    "level": "Advanced",
    "importance": 5,
    "url": "topics/automotive-communication/small-scale-fading-doppler.html",
    "summary": "While large-scale path loss determines average signal strength over hundreds of meters, small-scale fading describes rapid, deep fluctuations in signal amplitude and phase occurrin",
    "keywords": "Small-Scale Fading, RMS Delay Spread & Doppler Effect Wireless Fundamentals & Channel Models Advanced Automotive Communication Systems AELZG513 Maximum Doppler Frequency Shift Coherence Time of the Vehicular Channel What is the relationship between RMS delay spread and Coherence Bandwidth? Why is the Guard Interval in IEEE 802.11p set to 1.6 \u03bcs instead of 0.8 \u03bcs as in standard Wi-Fi? Explain the physics of Small-Scale Fading in automotive V2X channels. Derive formulas for Doppler shift, Coherence Time, RMS delay spread, and Coherence Bandwidth."
  },
  {
    "id": "in-vehicle-networks-ee-architecture",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "In-Vehicle Networks & Automotive E/E Architecture Evolution",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/in-vehicle-networks-ee-architecture.html",
    "summary": "Modern luxury and software-defined vehicles contain over 100 Electronic Control Units (ECUs) exchanging gigabytes of telemetry, control, and multimedia data every second. Automotiv",
    "keywords": "In-Vehicle Networks & Automotive E/E Architecture Evolution In-Vehicle Networks & Protocols Intermediate Automotive Communication Systems AELZG513 Bus Utilization Factor Calculation Why is automotive E/E architecture transitioning from Domain-based to Zonal-based? What is the primary function of an Automotive Central Gateway (CGW)? Analyze the evolution of automotive E/E architectures from distributed point-to-point to centralized Zonal architectures. Compare the protocols used in each domain and calculate the bus utilization for a multi-ECU CAN cluster."
  },
  {
    "id": "can-protocol-overview",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN Protocol Architecture & Differential Physical Layer",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/can-protocol-overview.html",
    "summary": "Controller Area Network (CAN), standardized under ISO 11898, is the most widely adopted in-vehicle networking standard in automotive history. Developed by Robert Bosch GmbH, CAN is",
    "keywords": "CAN Protocol Architecture & Differential Physical Layer In-Vehicle Networks & Protocols Intermediate Automotive Communication Systems AELZG513 Equivalent Bus Termination Resistance What is the difference between Dominant and Recessive states on a CAN bus? Why are 120-ohm termination resistors placed at the ends of a CAN network? Explain the complete physical layer architecture of ISO 11898-2 High-Speed CAN. Describe differential signaling levels, the wired-AND mechanism, noise immunity, and termination resistor design."
  },
  {
    "id": "can-frame-format",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN Frame Architecture & Field Formats",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/can-frame-format.html",
    "summary": "The CAN Data Link Layer defines four distinct frame types for bus communication: Data Frame (transmits payload data), Remote Frame (solicits data transmission), Error Frame (signal",
    "keywords": "CAN Frame Architecture & Field Formats In-Vehicle Networks & Protocols Intermediate Automotive Communication Systems AELZG513 Standard CAN Frame Bit Count & Transmission Time What is the function of the IDE bit in a CAN frame? How does the transmitter know if a CAN frame was successfully received? Draw and label the complete bit-level frame structure of a Standard CAN 2.0A Data Frame. Explain the function of each field in detail and compute the worst-case transmission time for an 8-byte message at 500 kbps."
  },
  {
    "id": "can-arbitration-mechanism",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN Bus Non-Destructive Bitwise Arbitration",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/can-arbitration-mechanism.html",
    "summary": "In a distributed multi-master vehicle network, multiple Electronic Control Units (ECUs) may attempt to transmit messages simultaneously when the bus becomes idle. Controller Area N",
    "keywords": "CAN Bus Non-Destructive Bitwise Arbitration In-Vehicle Networks & Protocols Intermediate Automotive Communication Systems AELZG513 Maximum Propagation Delay Constraint for Arbitration Why does a lower numerical CAN ID have higher priority during arbitration? What does a CAN controller do the exact moment it loses arbitration? Explain the complete mechanism of CAN Non-Destructive Bitwise Arbitration with a step-by-step numerical trace comparing three competing nodes (ID 0x100, 0x104, 0x200). Contrast this mechanism with Ethernet CSMA/CD."
  },
  {
    "id": "can-bit-stuffing-and-timing",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN Bit Stuffing Mechanism, Bit Timing & Synchronization",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Advanced",
    "importance": 5,
    "url": "topics/automotive-communication/can-bit-stuffing-and-timing.html",
    "summary": "To maintain clock synchronization between unsynchronized node crystal oscillators without dedicating a separate clock wire, CAN employs two critical lower-layer mechanisms: Bit Stu",
    "keywords": "CAN Bit Stuffing Mechanism, Bit Timing & Synchronization In-Vehicle Networks & Protocols Advanced Automotive Communication Systems AELZG513 Nominal Bit Rate and Time Quanta Equations Why is bit stuffing used in Controller Area Networks? Which fields in a CAN 2.0A frame are NOT subject to bit stuffing? Explain the complete CAN Bit Timing model and Bit Stuffing mechanism. Calculate the register settings (PRESDIV, PROPSEG, PSEG1, PSEG2) to achieve 500 kbps at an 80% sample point from an 80 MHz clock source."
  },
  {
    "id": "can-error-handling-fault-confinement",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN Error Detection Types & Fault Confinement Mechanism",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Advanced",
    "importance": 5,
    "url": "topics/automotive-communication/can-error-handling-fault-confinement.html",
    "summary": "To ensure extreme reliability in safety-critical automotive systems, CAN implements five distinct mathematical and logical error-detection mechanisms. Furthermore, to prevent a sin",
    "keywords": "CAN Error Detection Types & Fault Confinement Mechanism In-Vehicle Networks & Protocols Advanced Automotive Communication Systems AELZG513 Transmitter Bus-Off Time Calculation What are the 5 types of errors detected by a CAN controller? What is the difference between an Active Error Flag and a Passive Error Flag? Describe the complete CAN Fault Confinement mechanism. Detail the five error types, the role of TEC/REC error counters, and the state transitions between Error Active, Error Passive, and Bus-Off with a state diagram."
  },
  {
    "id": "can-fd-protocol",
    "subject": "automotive-communication",
    "subject_code": "AELZG513",
    "subject_title": "Automotive Communication Systems",
    "title": "CAN with Flexible Data-Rate (CAN-FD) Architecture",
    "module": "In-Vehicle Networks & Protocols",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-communication/can-fd-protocol.html",
    "summary": "As automotive electronic systems integrated ADAS sensors, multi-axis radar, and complex software-defined ECUs, Classic CAN 2.0 (limited to 1 Mbps and 8-byte payloads) became a band",
    "keywords": "CAN with Flexible Data-Rate (CAN-FD) Architecture In-Vehicle Networks & Protocols Intermediate Automotive Communication Systems AELZG513 Effective Data Throughput Gain in CAN-FD Why is the arbitration phase in CAN-FD kept at standard speed (e.g., 500 kbps) rather than 5 Mbps? What is the maximum payload size supported by CAN-FD? Explain the architecture and frame innovations of CAN-FD (ISO 11898-1:2015). Detail the Bit Rate Switch (BRS) mechanism, the expanded DLC mapping, and compute the throughput improvement for a 64-byte data payload."
  },
  {
    "id": "vehicle-classification-and-homologation",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "Automobile Classification, Homologation & Architecture",
    "module": "Vehicle Architecture & Classification",
    "level": "Beginner",
    "importance": 4,
    "url": "topics/automotive-vehicle/vehicle-classification-and-homologation.html",
    "summary": "Automotive engineering requires strict adherence to international classification standards and regulatory homologation frameworks. Vehicles are classified based on purpose, gross v",
    "keywords": "Automobile Classification, Homologation & Architecture Vehicle Architecture & Classification Beginner Automotive Vehicle AELZC441 Gross Vehicle Weight (GVW) Equation What is the difference between Category M1 and Category N1 vehicles? What is automotive homologation? Explain the vehicle classification framework according to UN ECE / AIS standards. Outline the complete vehicle development lifecycle from concept design to homologation."
  },
  {
    "id": "tractive-force-and-road-loads",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "Tractive Effort & Longitudinal Road Resistances",
    "module": "Vehicle Dynamics & Propulsion",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-vehicle/tractive-force-and-road-loads.html",
    "summary": "For a vehicle to move forward, accelerate, or climb a hill, the powertrain must deliver sufficient torque to the driven wheels to generate a longitudinal tractive force ($F_t$) at ",
    "keywords": "Tractive Effort & Longitudinal Road Resistances Vehicle Dynamics & Propulsion Intermediate Automotive Vehicle AELZC441 Total Tractive Force Equation Engine / Motor Power Demand Why does aerodynamic power requirement scale with the cube of vehicle speed ($v^3$)? What physical mechanism produces rolling resistance in a pneumatic tyre? Derive the complete longitudinal equation of motion for a moving automobile. Calculate the wheel power required for a 1600 kg vehicle ($C_d = 0.28$, $A_f = 2.1\\text{ m}^2$, $f_{rr} = 0.012$) cruising at 120 km/h on a 3% uphill grade."
  },
  {
    "id": "powertrain-architectures-and-layouts",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "Powertrain Architectures & Layout Topologies",
    "module": "Powertrain Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-vehicle/powertrain-architectures-and-layouts.html",
    "summary": "The powertrain represents the complete mechanical and electrical chain responsible for generating propulsion power and delivering it to the tyre-road contact patches. Powertrain ar",
    "keywords": "Powertrain Architectures & Layout Topologies Powertrain Fundamentals Intermediate Automotive Vehicle AELZC441 Overall Powertrain Gear Ratio and Wheel Speed What is torque steer and in which powertrain layout is it most prevalent? What is the primary function of a mechanical differential? Compare Front-Engine Front-Wheel Drive (FF), Front-Engine Rear-Wheel Drive (FR), and Dual-Motor EV architectures across weight distribution, packaging, handling characteristics, and manufacturing complexity."
  },
  {
    "id": "ic-engine-thermodynamic-cycles",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "IC Engine Fundamentals: 4-Stroke Otto & Diesel Cycles",
    "module": "IC Engine Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-vehicle/ic-engine-thermodynamic-cycles.html",
    "summary": "Internal Combustion (IC) engines convert the chemical energy stored in hydrocarbon fuels into mechanical shaft work through cyclic thermodynamic combustion processes. The two canon",
    "keywords": "IC Engine Fundamentals: 4-Stroke Otto & Diesel Cycles IC Engine Fundamentals Intermediate Automotive Vehicle AELZC441 Air-Standard Otto Cycle Thermal Efficiency Why is the compression ratio of a spark-ignition gasoline engine limited to approximately 12:1? What is clearance volume ($V_c$) and swept volume ($V_s$)? Draw and label the P-V diagram of an ideal 4-stroke Otto cycle. Derive the formula for its air-standard thermal efficiency and explain why actual indicated thermal efficiency is lower than ideal air-standard efficiency."
  },
  {
    "id": "engine-performance-parameters",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "Engine Performance Parameters: Power, Torque & BSFC",
    "module": "IC Engine Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-vehicle/engine-performance-parameters.html",
    "summary": "Evaluating the performance of internal combustion engines requires standardized mechanical, thermal, and volumetric parameters. Key metrics include Indicated Power (IP), Brake Powe",
    "keywords": "Engine Performance Parameters: Power, Torque & BSFC IC Engine Fundamentals Intermediate Automotive Vehicle AELZC441 Brake Power Formula Brake Specific Fuel Consumption (BSFC) What is the difference between Indicated Power (IP) and Brake Power (BP)? Why is Brake Mean Effective Pressure (BMEP) considered a better metric than peak torque for comparing engine designs? Define Indicated Power, Brake Power, Friction Power, Mechanical Efficiency, and BSFC. A 4-cylinder 4-stroke 2.0L engine running at 4500 RPM produces a dynamometer torque of 220 N\u00b7m while consuming 24.5 kg/h of fuel. Calculate its Brake Power, BMEP, and BSFC."
  },
  {
    "id": "transmission-systems-and-gearboxes",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "Transmission Systems: MT, AT, DCT, CVT & Planetary Gearsets",
    "module": "Powertrain Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/automotive-vehicle/transmission-systems-and-gearboxes.html",
    "summary": "Internal combustion engines produce useful torque only across a narrow speed range (1500 to 6000 RPM) and cannot start under zero-RPM load. The transmission system adapts high engi",
    "keywords": "Transmission Systems: MT, AT, DCT, CVT & Planetary Gearsets Powertrain Fundamentals Intermediate Automotive Vehicle AELZC441 Planetary Gear Ratio (Willis Kinematic Formula) What is the function of the stator in an automotive hydraulic torque converter? How does a Dual-Clutch Transmission (DCT) achieve gear shifts without torque interruption? Explain the construction and working principle of a modern automatic transmission torque converter. Include the impeller, turbine, stator, and lockup clutch with a fluid circulation diagram. Derive the planetary gear reduction ratio when the ring gear is held stationary."
  },
  {
    "id": "ev-motors-inverters-battery-packs",
    "subject": "automotive-vehicle",
    "subject_code": "AELZC441",
    "subject_title": "Automotive Vehicle",
    "title": "EV Powertrains: Traction Motors, Inverters & Battery Packs",
    "module": "Electric & Hybrid Vehicles",
    "level": "Advanced",
    "importance": 5,
    "url": "topics/automotive-vehicle/ev-motors-inverters-battery-packs.html",
    "summary": "Electric vehicle powertrains replace internal combustion engines and multi-speed gearboxes with three core high-voltage mechatronic subsystems: the High-Voltage Traction Battery Pa",
    "keywords": "EV Powertrains: Traction Motors, Inverters & Battery Packs Electric & Hybrid Vehicles Advanced Automotive Vehicle AELZC441 Battery Pack Capacity and Range Energy Calculation Why are 800V battery architectures rapidly replacing 400V systems in modern premium EVs? What is the difference between active and passive cell balancing in a Battery Management System (BMS)? Explain the architecture, power flow, and component interactions of an Electric Vehicle powertrain from high-voltage battery to driven wheels. Include the 3-phase inverter bridge, PMSM motor operation, and the BMS pre-charge sequencing procedure."
  },
  {
    "id": "automotive-systems-signal-flow",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Automotive Systems Architecture & Signal Flow",
    "module": "System Foundations",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/autotronics/automotive-systems-signal-flow.html",
    "summary": "Every automotive electronic system, regardless of its mechanical or software complexity, operates on one of three fundamental signal flows: Closed-Loop Control Applications (feedba",
    "keywords": "Automotive Systems Architecture & Signal Flow System Foundations Beginner Autotronics AEZG533 / AELZG533 Closed-Loop Negative Feedback Error Equation Why is an engine coolant temperature gauge considered an open-loop system while electronic cruise control is closed-loop? Can an engineer install a physical sensor to measure battery State of Charge (SOC) directly? Explain the three canonical signal flows in automotive electronic systems. Detail the generic instrumentation chain from physical measurand to actuator, using an engine electronic throttle control system as a worked example."
  },
  {
    "id": "resistors-and-voltage-divider-circuits",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Resistors, Voltage Dividers & Sensor Interfacing",
    "module": "Electrical & Electronics Fundamentals",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/autotronics/resistors-and-voltage-divider-circuits.html",
    "summary": "Resistors are passive dissipative circuit components that convert electrical energy into heat, governed by Ohm's Law. In automotive electronics, resistor networks form the fundamen",
    "keywords": "Resistors, Voltage Dividers & Sensor Interfacing Electrical & Electronics Fundamentals Beginner Autotronics AEZG533 / AELZG533 Voltage Divider Formula Current Divider Formula (Two Resistors) Why is a fixed pull-up resistor required when interfacing an NTC thermistor to a microcontroller ADC? What is the current divider formula for finding current through branch $R_1$ in a two-resistor parallel circuit? Derive the Voltage Divider and Current Divider formulas from fundamental Ohm's and Kirchhoff's circuit laws. Design an automotive Throttle Position Sensor (TPS) circuit operating from a 5V supply and calculate its output voltage across wiper angles of 0%, 50%, and 100%."
  },
  {
    "id": "capacitors-and-energy-storage",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Capacitors, Energy Storage & RC Timing Circuits",
    "module": "Electrical & Electronics Fundamentals",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/autotronics/capacitors-and-energy-storage.html",
    "summary": "Capacitors are passive electronic components that store electrical energy in an electrostatic field between conductive plates separated by a dielectric medium. In automotive electr",
    "keywords": "Capacitors, Energy Storage & RC Timing Circuits Electrical & Electronics Fundamentals Beginner Autotronics AEZG533 / AELZG533 Capacitor Energy Storage Formula RC Time Constant and Transient Voltage Why does a capacitor act as an open circuit in DC steady state? How do capacitors combine in parallel versus series? Derive the differential equation for an RC series charging circuit. Plot and explain the voltage and current transient curves as a function of the time constant $\\tau = RC$."
  },
  {
    "id": "inductors-magnetism-and-transformers",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Inductors, Magnetic Fields & Ignition Coil Transformers",
    "module": "Electrical & Electronics Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/autotronics/inductors-magnetism-and-transformers.html",
    "summary": "Inductors are passive electromagnetic components that store energy in a magnetic field generated by current flow through a conductor coil. Governed by Faraday's Law of Induction an",
    "keywords": "Inductors, Magnetic Fields & Ignition Coil Transformers Electrical & Electronics Fundamentals Intermediate Autotronics AEZG533 / AELZG533 Inductor Voltage & Energy Equations Transformer Turns Ratio and Voltage Step-Up What is an inductive flyback voltage spike and why does it occur? What is the purpose of a freewheeling diode connected across a relay coil? Explain the working principle of an automotive electronic ignition system. Describe the energy charging phase, magnetic field collapse, and transformer step-up mechanism that produces a 25 kV spark from a 12V battery."
  },
  {
    "id": "circuit-laws-mesh-nodal-thevenin",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Circuit Theorems: KCL, KVL, Mesh, Nodal & Th\u00e9venin Equivalent",
    "module": "Electrical & Electronics Fundamentals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/autotronics/circuit-laws-mesh-nodal-thevenin.html",
    "summary": "Complex automotive sensor interfaces, electronic control units, and power distribution networks are analyzed using fundamental circuit theorems: Kirchhoff's Current Law (KCL), Kirc",
    "keywords": "Circuit Theorems: KCL, KVL, Mesh, Nodal & Th\u00e9venin Equivalent Electrical & Electronics Fundamentals Intermediate Autotronics AEZG533 / AELZG533 Th\u00e9venin Load Current and Voltage Equations Maximum Power Transfer Equation State Kirchhoff's Current Law (KCL) and the fundamental physical conservation principle behind it. How are independent voltage and current sources treated when determining Th\u00e9venin resistance ($R_{th}$)? State Th\u00e9venin's Theorem. For a 24V supply connected to a bridge circuit ($R_1 = 10\\ \\Omega$, $R_2 = 40\\ \\Omega$, $R_3 = 20\\ \\Omega$, $R_4 = 30\\ \\Omega$), derive the complete Th\u00e9venin equivalent circuit across the bridge output terminals and calculate the load current through a $50\\ \\Omega$ meter."
  },
  {
    "id": "transistors-bjt-and-mosfet-switches",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Transistors as Switches: BJT & Power MOSFET Driving",
    "module": "Semiconductors & Power Electronics",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/autotronics/transistors-bjt-and-mosfet-switches.html",
    "summary": "Microcontrollers operate on sensitive 3.3V or 5V digital logic and can output only 10 to 25 mA of current. Automotive actuators (fuel injectors, ignition coils, solenoids, headlamp",
    "keywords": "Transistors as Switches: BJT & Power MOSFET Driving Semiconductors & Power Electronics Intermediate Autotronics AEZG533 / AELZG533 BJT Base Resistor Sizing (Forced Saturation) MOSFET Conduction Power Loss Why is a Power MOSFET preferred over a BJT for high-current automotive switching? What is the purpose of the 10 k\u03a9 pull-down resistor connected to the gate of an N-MOSFET? Explain the operation of BJT and Power MOSFET switches in automotive electronic systems. Design an NPN BJT switch circuit to drive a 12V / 300 mA solenoid from a 3.3V microcontroller GPIO. Compare Low-Side vs High-Side switching topologies."
  },
  {
    "id": "operational-amplifiers-in-signal-conditioning",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Operational Amplifiers & Sensor Signal Conditioning",
    "module": "Analog Signal Conditioning",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/autotronics/operational-amplifiers-in-signal-conditioning.html",
    "summary": "Automotive sensors (piezoelectric knock sensors, thermocouples, strain gauge load cells, and variable reluctance wheel speed sensors) output raw electrical signals in the microvolt",
    "keywords": "Operational Amplifiers & Sensor Signal Conditioning Analog Signal Conditioning Intermediate Autotronics AEZG533 / AELZG533 Non-Inverting Amplifier Gain Formula Active Low-Pass Filter Cutoff Frequency State the two 'Golden Rules' of ideal operational amplifiers with negative feedback. Why is a voltage follower (buffer) inserted between a high-impedance sensor and an ADC pin? Derive the closed-loop voltage gain expressions for an Inverting and a Non-Inverting Op-Amp circuit from fundamental Golden Rules. Design a signal conditioning circuit to amplify a 0\u2013100 mV thermocouple signal to 0\u20135.0 V with a 20 Hz low-pass filter."
  },
  {
    "id": "analog-to-digital-and-digital-to-analog-converters",
    "subject": "autotronics",
    "subject_code": "AEZG533 / AELZG533",
    "subject_title": "Autotronics",
    "title": "Data Converters: ADC & DAC Architectures in Automotive ECUs",
    "module": "Analog-to-Digital Conversion",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/autotronics/analog-to-digital-and-digital-to-analog-converters.html",
    "summary": "Microcontrollers operate strictly in the discrete digital domain (1s and 0s), whereas automotive physical phenomena (temperatures, manifold pressures, throttle angles, and oxygen l",
    "keywords": "Data Converters: ADC & DAC Architectures in Automotive ECUs Analog-to-Digital Conversion Intermediate Autotronics AEZG533 / AELZG533 ADC Output Code and Voltage Relationship Signal-to-Quantization-Noise Ratio (SQNR) What is the LSB step size and quantization error of a 10-bit ADC operating from a 5.0V reference? State the Nyquist-Shannon Sampling Theorem and explain the consequence of violating it. Explain the architecture and complete step-by-step conversion cycle of a Successive Approximation Register (SAR) ADC. For a 4-bit SAR ADC with $V_{ref} = 5.0\\text{ V}$ and analog input $V_{in} = 3.2\\text{ V}$, trace the comparator decisions and register contents across all 4 clock cycles."
  },
  {
    "id": "embedded-systems-overview-and-classification",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "Embedded Systems Foundations & Real-Time Constraints",
    "module": "Embedded Fundamentals",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/embedded-system-design/embedded-systems-overview-and-classification.html",
    "summary": "An embedded system is an application-specific, purpose-built computing system that integrates processing cores, memory, and specialized hardware peripherals into a larger mechanica",
    "keywords": "Embedded Systems Foundations & Real-Time Constraints Embedded Fundamentals Beginner Embedded System Design AEZG512 / AELZC512 Real-Time Schedulability Test (Rate Monotonic) What is the difference between a Hard Real-Time system and a Soft Real-Time system? What are the primary hardware components integrated inside a single-chip microcontroller? Define an Embedded System. Explain its structural building blocks and classify embedded systems based on real-time performance and architectural generations with automotive examples."
  },
  {
    "id": "microprocessor-vs-microcontroller-architectures",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "Microprocessor vs Microcontroller & Processor Architectures",
    "module": "Embedded Fundamentals",
    "level": "Beginner",
    "importance": 5,
    "url": "topics/embedded-system-design/microprocessor-vs-microcontroller-architectures.html",
    "summary": "The selection between a Microprocessor (MPU) and a Microcontroller (MCU) represents the fundamental architectural division in computer engineering. Microprocessors feature high-spe",
    "keywords": "Microprocessor vs Microcontroller & Processor Architectures Embedded Fundamentals Beginner Embedded System Design AEZG512 / AELZC512 Processor Instruction Execution Time What is the Von Neumann Bottleneck? What is meant by a 'Load-Store' architecture in RISC processors? Compare Microprocessors and Microcontrollers across hardware integration, memory architecture (Von Neumann vs Harvard), instruction sets (CISC vs RISC), and power consumption. Explain why automotive real-time ECUs are built using RISC Harvard microcontrollers."
  },
  {
    "id": "arm-cortex-m4-core-architecture",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "ARM Cortex-M4 Core Architecture & Bus Matrix",
    "module": "Processor Architecture",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/embedded-system-design/arm-cortex-m4-core-architecture.html",
    "summary": "The ARM Cortex-M4 is an industry-standard 32-bit RISC processor core engineered specifically for deterministic, high-performance, cost-sensitive real-time embedded control applicat",
    "keywords": "ARM Cortex-M4 Core Architecture & Bus Matrix Processor Architecture Intermediate Embedded System Design AEZG512 / AELZC512 Pipeline Throughput and Branch Penalty Calculation What are the four primary external buses in the ARM Cortex-M4 bus matrix? What happens inside the Cortex-M4 3-stage pipeline when a branch instruction is taken? Explain the internal core architecture of the ARM Cortex-M4 processor. Describe the 3-stage instruction pipeline, the multi-layer AHB-Lite bus matrix, and the hardware DSP/FPU capabilities with an architectural block diagram."
  },
  {
    "id": "arm-cortex-m4-programmers-model",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "ARM Cortex-M4 Programmer's Model & Register Set",
    "module": "Processor Architecture",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/embedded-system-design/arm-cortex-m4-programmers-model.html",
    "summary": "The programmer's model defines the register set, operating modes, privilege levels, and execution states visible to software running on the ARM Cortex-M4 core. Mastering the 16 cor",
    "keywords": "ARM Cortex-M4 Programmer's Model & Register Set Processor Architecture Intermediate Embedded System Design AEZG512 / AELZC512 AAPCS Register Calling Convention Mapping What is the difference between the Main Stack Pointer (MSP) and the Process Stack Pointer (PSP)? What are the two processor operating modes in ARM Cortex-M4? Describe the complete Programmer's Model of the ARM Cortex-M4 processor. Detail the 16 core registers, the dual banked stack pointers, the xPSR register fields, and the transition between Thread Mode and Handler Mode."
  },
  {
    "id": "arm-cortex-m4-nvic-and-exceptions",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "Nested Vectored Interrupt Controller (NVIC) & Exception Handling",
    "module": "Interrupts & Peripherals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/embedded-system-design/arm-cortex-m4-nvic-and-exceptions.html",
    "summary": "Real-time automotive microcontrollers must respond instantaneously to asynchronous external events (such as CAN message reception, timer overflows, and ADC conversion completions).",
    "keywords": "Nested Vectored Interrupt Controller (NVIC) & Exception Handling Interrupts & Peripherals Intermediate Embedded System Design AEZG512 / AELZC512 Interrupt Latency Calculation What eight registers are automatically pushed onto the stack by hardware during ARM Cortex-M4 interrupt entry? What is Tail-Chaining in the ARM Cortex-M4 NVIC? Explain the complete ARM Cortex-M4 Exception Model and NVIC operation. Detail the vector table layout, the 12-cycle hardware stacking sequence, priority grouping (preemption vs sub-priority), and the Tail-Chaining and Late-Arrival optimizations."
  },
  {
    "id": "s32k144-gpio-configuration-and-driver",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "NXP S32K144 GPIO Architecture & Low-Level Driver Development",
    "module": "Microcontroller Peripherals",
    "level": "Intermediate",
    "importance": 5,
    "url": "topics/embedded-system-design/s32k144-gpio-configuration-and-driver.html",
    "summary": "General Purpose Input/Output (GPIO) ports provide the primary digital interface between the NXP S32K144 automotive microcontroller and external hardware circuits (switches, LEDs, r",
    "keywords": "NXP S32K144 GPIO Architecture & Low-Level Driver Development Microcontroller Peripherals Intermediate Embedded System Design AEZG512 / AELZC512 GPIO Atomic Bit Mask Calculation What are the three essential register configuration steps required to initialize a GPIO output pin on the NXP S32K144? Why should an embedded developer use the PSOR and PCOR registers instead of writing directly to PDOR? Explain the complete 3-tier GPIO architecture of the NXP S32K144 microcontroller. Detail the roles of PCC, PORT, and GPIO register blocks. Write a complete bare-metal C program to configure Port D Pin 15 as an output LED and Port C Pin 12 as an input push-button with an internal pull-up resistor."
  },
  {
    "id": "s32k144-flexcan-automotive-network-controller",
    "subject": "embedded-system-design",
    "subject_code": "AEZG512 / AELZC512",
    "subject_title": "Embedded System Design",
    "title": "NXP S32K144 FlexCAN Controller & CAN-FD Implementation",
    "module": "Microcontroller Peripherals",
    "level": "Advanced",
    "importance": 5,
    "url": "topics/embedded-system-design/s32k144-flexcan-automotive-network-controller.html",
    "summary": "The FlexCAN module in the NXP S32K144 is a full-featured, silicon-hardened automotive network controller implementing ISO 11898-1 Classic CAN 2.0B and CAN-FD (Flexible Data-Rate) p",
    "keywords": "NXP S32K144 FlexCAN Controller & CAN-FD Implementation Microcontroller Peripherals Advanced Embedded System Design AEZG512 / AELZC512 CAN Bit Rate and Prescaler Formula What are the two steps required to put the S32K144 FlexCAN controller into Freeze Mode for configuration? What is the difference between Message Buffer Code `0b0100` and `0b0010` during FlexCAN reception? Explain the architecture and memory layout of Message Buffers in the NXP S32K144 FlexCAN module. Detail the bitfields of Word 0 (Control/Status) and Word 1 (ID). Calculate the register timing parameters to achieve a 500 kbps bit rate from a 40 MHz CAN clock."
  }
];
